export const comms = [
  {
    id: 1,
    date: "2024-10-21",
    time: "11:15 UTC",
    location: "Patrol Vessel Bravo",
    vessel_name: "Ocean Wanderer",
    coordinates: {
      latitude: "14°20'N",
      longitude: "72°15'W",
    },
    heading: null,
    speed: "10",
    imo_number: "8765432",
    priority: "routine",
    additional_info: "Routine patrol, calm sea",
  },
  {
    id: 2,
    date: "2024-10-21",
    time: "15:45 UTC",
    location: "Patrol Vessel Alpha",
    vessel_name: "Pacific Trader",
    coordinates: {
      latitude: "13°05'N",
      longitude: "71°45'W",
    },
    heading: null,
    speed: "12",
    imo_number: "9876543",
    priority: "unknown",
    additional_info: "No suspicious activity",
  },
  {
    id: 3,
    date: "2024-10-22",
    time: "09:30 UTC",
    location: "Patrol Vessel Delta",
    vessel_name: "Sea Guardian",
    coordinates: {
      latitude: "12°35'N",
      longitude: "73°20'W",
    },
    heading: "270",
    speed: "14",
    imo_number: "8765123",
    priority: "confidential",
    additional_info: "Monitoring nearby vessels",
  },
  {
    id: 4,
    date: "2024-10-22",
    time: "18:00 UTC",
    location: "Patrol Vessel Charlie",
    vessel_name: "Atlantic Voyager",
    coordinates: {
      latitude: "11°10'N",
      longitude: "70°00'W",
    },
    heading: "180",
    speed: "15",
    imo_number: "6549873",
    priority: "immediate",
    additional_info: "Possible fishing vessel sighted",
  },
  {
    id: 5,
    date: "2024-10-23",
    time: "07:50 UTC",
    location: "Patrol Vessel Echo",
    vessel_name: "Coastal Spirit",
    coordinates: {
      latitude: "15°30'N",
      longitude: "74°45'W",
    },
    heading: "90",
    speed: "13",
    imo_number: "9981234",
    priority: "urgent",
    additional_info: "No unusual behavior observed",
  },
  {
    id: 11,
    date: "2024-10-23",
    time: "07:50 UTC",
    location: "Patrol Vessel Echo",
    vessel_name: "Coastal Spirit",
    coordinates: {
      latitude: "15°30'N",
      longitude: "74°45'W",
    },
    heading: "90",
    speed: "13",
    imo_number: "9981234",
    priority: "urgent",
    additional_info: "No unusual behavior observed",
  },
  {
    id: 6,
    date: "2024-10-23",
    time: "13:10 UTC",
    location: "Patrol Vessel Foxtrot",
    vessel_name: "Mariner's Quest",
    coordinates: {
      latitude: "12°50'N",
      longitude: "73°00'W",
    },
    heading: "350",
    speed: "11",
    imo_number: "7654321",
    priority: "routine",
    additional_info: "Routine checks, all clear",
  },
  {
    id: 7,
    date: "2024-10-24",
    time: "16:30 UTC",
    location: "Patrol Vessel Golf",
    vessel_name: "Northern Explorer",
    coordinates: {
      latitude: "13°45'N",
      longitude: "72°30'W",
    },
    heading: null,
    speed: "12",
    imo_number: "2345678",
    priority: "routine",
    additional_info: "Clear skies, smooth waters",
  },
  {
    id: 8,
    date: "2024-10-25",
    time: "10:45 UTC",
    location: "Patrol Vessel Hotel",
    vessel_name: "Southern Ranger",
    coordinates: {
      latitude: "10°50'N",
      longitude: "69°55'W",
    },
    heading: "270",
    speed: "16",
    imo_number: "8765432",
    priority: "confidential",
    additional_info: "Detected minor engine noise",
  },
  {
    id: 9,
    date: "2024-10-26",
    time: "05:25 UTC",
    location: "Patrol Vessel India",
    vessel_name: "Eastern Star",
    coordinates: {
      latitude: "13°30'N",
      longitude: "71°30'W",
    },
    heading: "100",
    speed: "10",
    imo_number: "1234567",
    priority: "unknown",
    additional_info: "Routine monitoring",
  },
  {
    id: 10,
    date: "2024-10-26",
    time: "21:20 UTC",
    location: "Patrol Vessel Juliet",
    vessel_name: "Western Pioneer",
    coordinates: {
      latitude: "11°40'N",
      longitude: "70°40'W",
    },
    heading: "220",
    speed: "14",
    imo_number: "5678901",
    priority: "secret",
    additional_info: "Encountered moderate waves",
  },
];
export default comms;
